---
title: "QBS 103 Final (clean)"
output:
  pdf_document: default
  html_document: default
date: "2025-08-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
proj_genes <- read_csv("/Users/ayei/Desktop/QBS103_GSE157103_genes.csv")
```
```{r}
library(readr)
proj_matrix <- read_csv("/Users/ayei/Desktop/QBS103_GSE157103_series_matrix-1.csv")
```


```{r}
# Because I need to match the participant_id column/row position in order to link the two data sets, I first need to transpose the gene data so the participant_id become rows.

# Converting raw data to data frame
proj_genes_df <- as.data.frame(proj_genes)

# Setting the row names as the gene names
rownames(proj_genes_df) <- proj_genes_df[[1]]

# Now I have to remove the first column since I am using them as row names
proj_genes_df <- proj_genes_df[ , -1]         

# Transposing the data so that the gene names go across the top and the participant ID's became the column
new_proj_genes <- as.data.frame(t(proj_genes_df))

# Just doudble checking
# colnames(proj_matrix)
# colnames(new_proj_genes)

# Now I am adding a new column for "participant_id" to "new_proj_genes" with the row names, so that when I merge the the two data together, "participant ID" becomes its own column
new_proj_genes$participant_id <- rownames(new_proj_genes)
```

```{r}
# Merging the two datasets
merged_proj_data <- merge(proj_matrix, new_proj_genes, by = "participant_id")

# Double checking to see if the merge was successful
# summary(merged_proj_data)
```

```{r}
library(ggplot2)

# Making histogram for A1BG expression
ggplot(merged_proj_data, aes(x = A1BG)) +
  # Decided to make my binwidth 0.05 for more data points/make the data points more distinct
  # Also customized my colors
  geom_histogram(binwidth = 0.05, fill = "#D1514D", color = "black") +
  # Added a title, and x and y axis labels
  labs(title = "A1BG Expression", 
       x = "A1BG Expression", y = "Count") +
  # Set the theme to classic for a clean background
  theme_classic() +
  # Wanted to center my title
     ##https://www.r-bloggers.com/2025/03/how-to-center-ggplot-title-subtitle-and-caption-in-ggplot2-with-r/
  theme(plot.title = element_text(hjust = 0.5)) 
```
```{r}
# "age" was not being registered as a number, so I had to change the age column to numeric
merged_proj_data$age <- as.numeric(merged_proj_data$age)

# Making scatterplot for A1BG Expression vs Age
ggplot(merged_proj_data, aes(x = age, y = A1BG)) +
  # Customized the color and the size -- I set the size to 1 so that the point is more precise (when it was bigger, the points would overlap)
  geom_point(color = "#2E86AB", size = 1) +
  # Added a title, and x and y axis labels
  labs(title = "A1BG Expression vs Age",
       x = "Age", y = "A1BG Expression") +
  # Customized the scale for x axis to go up by 10s to make the plot easier to read
      ##https://www.sthda.com/english/wiki/ggplot2-axis-scales-and-transformations#google_vignette
  scale_x_continuous(breaks = seq(0, 100, by = 10)) +
  # Customized the scale for y axis to go up by 0.1 to make the plot easier to read
  scale_y_continuous(breaks = seq(0, 3, by = 0.1)) +
  # Set my theme to classic for a clean background
  theme_classic() +
  # Centered the title
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# Making boxplot for A1BG expression by disease status and sex
ggplot(merged_proj_data, aes(x = disease_status, y = A1BG, fill = sex)) +
  geom_boxplot() +
  # Customized the colors for sex
  scale_fill_manual(values = c("male"= '#849FE1', "female" = '#D1514D',"unknown" = '#E0C06B'),
  labels = function(x) tools::toTitleCase(as.character(x))) +
  scale_x_discrete(labels = function(x) tools::toTitleCase(as.character(x))) +
  # Added a title, and x and y labels
  labs(title = "A1BG Expression by Disease Status and Sex",
       x = "Disease Status", y = "A1BG Expression", fill = "Sex") +
  # Set my theme to classic for a clean background
  theme_classic() +
  # Centered my title
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
# install.packages('pheatmap')
library(pheatmap)

# Specifying ten genes for heatmap
ten_genes <- c("A1BG", "A1CF", "A2M", "A2ML1", "A3GALT2", "A4GNT", "AAAS", "AACS", "AADAC", "AADACL2")

# Getting expression values for the ten genes
gene_value_matrix <- merged_proj_data[, ten_genes]

# Making the participant ID's as the rownames
rownames(gene_value_matrix) <- merged_proj_data$participant_id

# Making mini data frame to match the participants w their disease status and sex
annotationData <- data.frame(
  row.names = merged_proj_data$participant_id,
  Disease = merged_proj_data$disease_status,
  Sex = merged_proj_data$sex)

annotationData$Disease <- as.character(annotationData$Disease)
annotationData$Disease <- factor(annotationData$Disease,
  levels = c("disease state: COVID-19", "disease state: non-COVID-19"),
  labels = tools::toTitleCase(c("disease state: COVID-19", "disease state: non-COVID-19")))

annotationData$Sex <- as.character(annotationData$Sex)
annotationData$Sex <- factor(annotationData$Sex,
  levels = c("male", "female", "unknown"),
  labels = tools::toTitleCase(c("male", "female", "unknown")))

# Setting colors for each of the variables
annotationColors <- list(
  Disease = c("Disease State: COVID-19" = "lightgreen", "Disease State: Non-COVID-19" = "forestgreen"),
  Sex = c("Male"= '#849FE1', "Female" = '#D1514D',"Unknown" = '#E0C06B'))

# Making the heatmap
pheatmap(
  t(gene_value_matrix),
  annotation_col = annotationData,
  annotation_colors = annotationColors,
  fontsize_col = 2,
  main = "Heatmap of 10 Genes with Sex and Disease Status")
```
```{r}
library(ggplot2)

# Making violin plot for A1BG expression by disease status and sex
ggplot(merged_proj_data, aes(x = disease_status, y = A1BG, fill = sex)) +
  geom_violin()+
  # Customized the colors for sex
  scale_fill_manual(values = c("male"= '#849FE1', "female" = '#D1514D',"unknown" = '#E0C06B'),
  labels = function(x) tools::toTitleCase(as.character(x))) +
  scale_x_discrete(labels = function(x) tools::toTitleCase(as.character(x))) +
  # Added a title, and x and y labels
  labs(title = "A1BG Expression by Disease Status and Sex",
       x = "Disease Status", y = "A1BG Expression", fill = "Sex") +
  # Set my theme to classic for a clean background
  theme_classic() +
  # Centered my title
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
library(dplyr)
library(knitr)
library(kableExtra)

set.seed(103)

# Making the summary table
my_table <- merged_proj_data %>%
  # Capitalizing the icu status
  mutate(icu_status = gsub("_", " ", icu_status),
         icu_status = tools::toTitleCase(tolower(icu_status))) %>%
  # Stratifying using icu status
  group_by(icu_status) %>%
  summarise(
    n = n(),
    
    # 1st categorical variable
    male.n = sum(sex == "male"),
    male.pct = round(100*mean(sex == "male"), 1),
    
    # 2nd categorical variable
    disease_status.yes = sum(disease_status == "disease state: COVID-19"),
    disease_status.yes.pct = round(100*mean(disease_status == "disease state: COVID-19"), 1),
    
    # 1st continuous variable
    age.mean = round(mean(age, na.rm = TRUE), 1),
    age.sd = round(sd(age, na.rm = TRUE), 1),
    
    # 2nd continuous variable
    gene.mean = round(mean(A1BG, na.rm = TRUE), 2),   # changed here
    gene.sd = round(sd(A1BG, na.rm = TRUE), 2),
    
    # 3rd continuous variable
    charlson_score.mean = round(mean(charlson_score, na.rm = TRUE), 2), # changed here
    charlson_score.sd = round(sd(charlson_score, na.rm = TRUE), 2)
  ) %>%
  
  mutate(
    'Sex (male)' = paste0(male.n, " (", male.pct, "%)"),
    'Disease status (COVID-19)' = paste0(disease_status.yes, " (", disease_status.yes.pct, "%)"),
    'Age' = paste0(age.mean, " (", age.sd, ")"),
    'A1BG Gene Expression' = paste0(gene.mean, " (", gene.sd, ")"),
    'Charlson Score' = paste0(charlson_score.mean, " (", charlson_score.sd, ")")
  ) %>%
  
  select(icu_status, n, 'Sex (male)', 'Disease status (COVID-19)', 'Age', 'A1BG Gene Expression', 'Charlson Score')

```


```{r}
# Making LaTex table 
print_table <- my_table
# Editing the column name for icu status
colnames(print_table)[colnames(print_table) == "icu_status"] <- "ICU Status"

kable(print_table, format = "latex", booktabs = TRUE,
      caption = "Summary Statistics Stratified by ICU Status",
      col.names = colnames(print_table)) %>%
  kable_styling(latex_options = c("hold_position", "striped"))

```

```{r}
citation("readr")
citation("ggplot2")
citation("pheatmap")
citation("knitr")
citation("dplyr")
citation("kableExtra")
```


